spring:
  application:
    name: ai-sync-hub-user
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: users
  datasource:
    hikari:
      maxLifetime: 30000
      idleTimeout: 30000
  profiles:
    active: default

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: metrics, health, info
